name: LingChat
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - pip
  - cpuonly
  - pytorch > =2.5.0
  - pyperclip
  - openai>=1.97.0
  - libtorch>=2.5.0=cpu_*
  - transformers>=4.50.0
  - sentence-transformers>=4.1.0
  - websockets>=15.0
  - fastapi>=0.115.0
  - aiohttp>=3.12.0
  - python-multipart>=0.0.19
  - chromadb>=1.0.0
  - uvicorn>=0.34.0
  - mss>=9.0.0
  - google-generativeai 
  - rank-bm25 >= 0.2.2
  - mcp >= 1.10.0
  - fastmcp >= 2.9.0

