<template>
  <img
    src="../../../../assets/images/LingChatLogo.webp"
    alt="LingChatLogo"
    class="cursor-pointer
      hover:scale-105
      transition-transform
      duration-300
      absolute
      top-0
      right-0
      h-auto
      w-auto
      max-w-[40vw]
      drop-shadow-[0_4px_8px_rgba(0,0,0,0.3)]
      z-5"
    v-bind="$attrs"
  />
</template>
