[project]
name = "NeoChat" 
version = "0.1.0"         
description = "none"
requires-python = ">=3.8"   # 项目兼容的Python版本

dependencies = [
    "pyyaml",
    "python-dotenv",
    "requests",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"