openai:
  api_key: "your-openai-key"
  base_url: "https://api.openai.com/v1"

deepseek:
  api_key: "your-deepseek-key"
  base_url: "https://api.deepseek.com/v1"

spark:
  app_id: "your-app-id"
  api_key: "your-spark-key"
  api_secret: "your-api-secret"

qwen:
  api_key: "your-qwen-key"

ollama:
  base_url: "http://localhost:11434" #If you are using the ollama model, please use the (ollama-modelname) to call

my_api_keys:
  - "your-api-key-1"
  - "your-api-key-2"
