services:
  golang-backend:
    build:
      context: backend/go-impl/
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
      - "9876:9876"
    volumes:
      - ./volume/data:/app/audio
    env_file:
      - backend/go-impl/.env
    networks:
      - app-network

  node-frontend:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"
    volumes:
      - ./volume/data:/app/public/audio
    depends_on:
      - golang-backend
    env_file:
      - backend/go-impl/.env
    networks:
      - app-network

  predictor-server:
    build:
      context: .
      dockerfile: Dockerfile-predictor
    ports:
      - "8000:8000"
    networks:
      - app-network

# 如果使用vits语音docker，请将其docker加入lingchat container network, 否则后端无法与其通信生成语音
# docker network connect lingchat_app-network vits-simple-api-vits

networks:
  app-network:
    driver: bridge